/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_phieuthue;
import DTO.DTO_phong;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ADMIN
 */
public class GUI_phieuThue extends javax.swing.JFrame {

    /**
     * Creates new form GUI_phieuThue
     */
    public GUI_phieuThue() {
        initComponents();
    }
    public static LocalDate date = java.time.LocalDate.now();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_hoanthanh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_maphong = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_tenphong = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_tennhanvien = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_giaphong = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tenKH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        spn_tuoi = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        txt_CMND = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        spn_songay = new javax.swing.JSpinner();
        lbl_maNV = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_ngaythue = new javax.swing.JLabel();
        btn_thue = new javax.swing.JButton();
        btn_hoanthanh1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PHiếu thuê");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Phiếu thuê");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_hoanthanh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_hoanthanh.setText("In Phiếu");
        btn_hoanthanh.setEnabled(false);
        btn_hoanthanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoanthanhActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hoanthanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 640, -1, 44));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Mã phòng:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        lbl_maphong.setText("0");
        lbl_maphong.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_maphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 110, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Tên phòng:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        lbl_tenphong.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_tenphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 135, 30));

        jLabel4.setText("Tên người dùng:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 124, -1, -1));

        lbl_tennhanvien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_tennhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 120, 213, 30));

        jLabel5.setText("Giá phòng:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 191, -1, -1));

        lbl_giaphong.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_giaphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 191, 140, 23));

        jLabel6.setText("Tên khách thuê:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 264, -1, -1));

        txt_tenKH.setEnabled(false);
        jPanel1.add(txt_tenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 261, 218, -1));

        jLabel7.setText("Tuổi:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 330, -1, -1));

        spn_tuoi.setEnabled(false);
        jPanel1.add(spn_tuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 327, 71, -1));

        jLabel8.setText("Số điện thoại:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 395, -1, -1));

        jLabel9.setText("Số CMND:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 456, -1, -1));

        txt_sdt.setEnabled(false);
        jPanel1.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 392, 218, -1));

        txt_CMND.setEnabled(false);
        jPanel1.add(txt_CMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 453, 218, -1));

        jLabel10.setText("Số ngày thuê:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 594, -1, -1));

        spn_songay.setEnabled(false);
        jPanel1.add(spn_songay, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 591, 69, -1));
        jPanel1.add(lbl_maNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 120, 85, 20));

        jLabel11.setText("Ngày thuê:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 523, -1, -1));

        lbl_ngaythue.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_ngaythue, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 515, 218, 24));

        btn_thue.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_thue.setText("Thuê");
        btn_thue.setEnabled(false);
        btn_thue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thueActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thue, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 640, 82, 44));

        btn_hoanthanh1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_hoanthanh1.setText("Hoàn thành");
        btn_hoanthanh1.setEnabled(false);
        btn_hoanthanh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoanthanh1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hoanthanh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 640, -1, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel1)
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (GUI.GUI_phong.trangthai.equals("dangthue")) {
            spn_songay.setEnabled(true);
            btn_hoanthanh.setEnabled(true);
        } else {
            txt_tenKH.setEnabled(true);
            txt_sdt.setEnabled(true);
            txt_CMND.setEnabled(true);
            spn_tuoi.setEnabled(true);
            btn_thue.setEnabled(true);
        }

        ResultSet rs = DAO.DAO_phong.laydulieu_Theoten(GUI.GUI_phong.tenPhong);
//        DTO.DTO_phong phong=new DTO_phong();
//        try {
//            if (rs.next()) {
//                phong.setMaphong(rs.getInt("maphong"));
//                phong.setTenPhong(rs.getString("tenphong"));
//                phong.setDientich(rs.getInt("dientich"));
//                phong.setGia(rs.getInt("gia"));
//            }
//        } catch (SQLException ex) {
//           thongbao.thongbao("", "");
//        }
        try {
            if (rs.next()) {
                lbl_maphong.setText(rs.getString("maphong"));
                lbl_tenphong.setText(rs.getString("tenphong"));
                lbl_giaphong.setText(rs.getString("gia"));
            }
        } catch (SQLException ex) {
            thongbao.thongbao("lỗi đổ dữ liệu", "thông báo");
        }
        lbl_tennhanvien.setText(BLL.BLL_dangnhap.hovaten);
        lbl_ngaythue.setText(date.toString());

    }//GEN-LAST:event_formWindowOpened

    private void btn_thueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thueActionPerformed
        DTO.DTO_phieuthue pt = new DTO_phieuthue();
        try {
            pt.setMaphong(Integer.parseInt(lbl_maphong.getText()));
            
            pt.setTenphong(lbl_tenphong.getText());
           
            pt.setTenuser(lbl_tennhanvien.getText());
           
            pt.setGiaphong(Double.parseDouble(lbl_giaphong.getText()));
           
            pt.setTenKH(txt_tenKH.getText());
            pt.setTuoi(Integer.parseInt(spn_tuoi.getValue().toString()));
            pt.setSdt(txt_sdt.getText());
            pt.setCMND(txt_CMND.getText());

            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-mm-dd");

            pt.setNgaythue(formatter.parse(lbl_ngaythue.getText()));
        } catch (ParseException ex) {
            thongbao.thongbao("lỗi", "");
        }
        DAO.DAO_phieuthue.them(pt);

    }//GEN-LAST:event_btn_thueActionPerformed

    private void btn_hoanthanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoanthanhActionPerformed
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Lưu phiếu thuê ra Excel");
    fileChooser.setSelectedFile(new File("phieu_thue.xlsx"));

    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection != JFileChooser.APPROVE_OPTION) return;

    File fileToSave = fileChooser.getSelectedFile();

    try (Workbook workbook = new XSSFWorkbook()) {
        Sheet sheet = workbook.createSheet("Phiếu Thuê");

        // Ghi dòng tiêu đề
        Row header = sheet.createRow(0);
        header.createCell(0).setCellValue("Thông tin phiếu thuê");

        // Dữ liệu: mỗi cặp label - value là 1 dòng
        int rowIndex = 2;

        rowIndex = createRow(sheet, rowIndex, "Mã phòng", lbl_maphong.getText());
        rowIndex = createRow(sheet, rowIndex, "Tên phòng", lbl_tenphong.getText());
        rowIndex = createRow(sheet, rowIndex, "Tên nhân viên", lbl_tennhanvien.getText());
        rowIndex = createRow(sheet, rowIndex, "Mã NV", lbl_maNV.getText());
        rowIndex = createRow(sheet, rowIndex, "Giá phòng", lbl_giaphong.getText());
        rowIndex = createRow(sheet, rowIndex, "Tên khách thuê", txt_tenKH.getText());
        rowIndex = createRow(sheet, rowIndex, "Tuổi", spn_tuoi.getValue().toString());
        rowIndex = createRow(sheet, rowIndex, "Số điện thoại", txt_sdt.getText());
        rowIndex = createRow(sheet, rowIndex, "Số CMND", txt_CMND.getText());
        rowIndex = createRow(sheet, rowIndex, "Ngày thuê", lbl_ngaythue.getText());
        rowIndex = createRow(sheet, rowIndex, "Số ngày thuê", spn_songay.getValue().toString());

        // Ghi file
        FileOutputStream fileOut = new FileOutputStream(fileToSave);
        workbook.write(fileOut);
        fileOut.close();

        JOptionPane.showMessageDialog(this, "Xuất phiếu thuê thành công!");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi ghi file Excel: " + ex.getMessage());
    }
    }//GEN-LAST:event_btn_hoanthanhActionPerformed
    private int createRow(Sheet sheet, int rowIndex, String label, String value) {
        Row row = sheet.createRow(rowIndex);
        row.createCell(0).setCellValue(label);
        row.createCell(1).setCellValue(value);
        return rowIndex + 1;
}
    private void btn_hoanthanh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoanthanh1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_hoanthanh1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_phieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_phieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_phieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_phieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_phieuThue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hoanthanh;
    private javax.swing.JButton btn_hoanthanh1;
    private javax.swing.JButton btn_thue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_giaphong;
    private javax.swing.JLabel lbl_maNV;
    private javax.swing.JLabel lbl_maphong;
    private javax.swing.JLabel lbl_ngaythue;
    private javax.swing.JLabel lbl_tennhanvien;
    private javax.swing.JLabel lbl_tenphong;
    private javax.swing.JSpinner spn_songay;
    private javax.swing.JSpinner spn_tuoi;
    private javax.swing.JTextField txt_CMND;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenKH;
    // End of variables declaration//GEN-END:variables
}
