/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.DTO_NV;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class GUI_nhanvien extends javax.swing.JFrame {



    public GUI_nhanvien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_ten = new javax.swing.JTextField();
        cbb_gioitinh = new javax.swing.JComboBox<>();
        txt_sdt = new javax.swing.JTextField();
        txt_luong = new javax.swing.JTextField();
        txt_diachi = new javax.swing.JTextField();
        txt_ghichu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_nhanvien = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txt_timkiem = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        txt_ngaylam = new com.toedter.calendar.JDateChooser();
        txt_ngaysinh = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txt_bangcap = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nhân viên");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Quản lý nhân viên");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tên nhân viên:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Giới tính:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Ngày sinh:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Số điện thoại:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Ngày làm:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Lương:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Địa chỉ:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Ghi chú:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));
        getContentPane().add(txt_ten, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 242, -1));

        cbb_gioitinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ", "Khác" }));
        getContentPane().add(cbb_gioitinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 92, -1));
        getContentPane().add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 250, -1));

        txt_luong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_luongKeyReleased(evt);
            }
        });
        getContentPane().add(txt_luong, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 242, -1));
        getContentPane().add(txt_diachi, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 242, -1));
        getContentPane().add(txt_ghichu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 242, -1));

        tbl_nhanvien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã nhân viên", "Tên nhân viên", "Giới tính", "Ngày sinh", "Số điện thoại", "Ngày làm", "Lương", "Địa chỉ", "Ghi chú", "Bằng Cấp"
            }
        ));
        tbl_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_nhanvienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_nhanvien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 680, 183));

        jLabel10.setText("Tìm kiếm:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        txt_timkiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_timkiemKeyReleased(evt);
            }
        });
        getContentPane().add(txt_timkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 260, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 120, 50));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 120, 50));

        btn_sua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.setEnabled(false);
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 120, 50));
        getContentPane().add(txt_ngaylam, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 250, -1));
        getContentPane().add(txt_ngaysinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 250, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Bằng Cấp:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        txt_bangcap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Không Có", "Cử Nhân", "Thạc Sĩ", "Tiến SĨ" }));
        getContentPane().add(txt_bangcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 130, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        BLL.BLL_dodulieuNV.dodulieuNV(tbl_nhanvien);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DTO.DTO_NV nv = new DTO_NV();
    nv.setTen(txt_ten.getText());
    nv.setGioitinh(cbb_gioitinh.getSelectedItem().toString());

    // ✅ Ngày sinh
    Date ngaysinhDate = txt_ngaysinh.getDate();
    if (ngaysinhDate != null) {
        nv.setNgaysinh(new SimpleDateFormat("yyyy-MM-dd").format(ngaysinhDate));
    } else {
        nv.setNgaysinh(null); // hoặc giá trị mặc định
    }

    nv.setSdt(txt_sdt.getText());

    // ✅ Ngày làm
    Date ngaylamDate = txt_ngaylam.getDate();
    if (ngaylamDate != null) {
        nv.setNgaylam(new SimpleDateFormat("yyyy-MM-dd").format(ngaylamDate));
    } else {
        nv.setNgaylam(null);
    }

    nv.setLuong(ChuyenDoi.ChuyenSangSo(txt_luong.getText()));
    nv.setDiachi(txt_diachi.getText());
    nv.setGhichu(txt_ghichu.getText());
    nv.setBangCap(txt_bangcap.getSelectedItem().toString());

    boolean kt = BLL.BLL_NV.ktNV(nv);
    if (kt) {
        DAO.DAO_nhanvien.themNV(nv);
        BLL.BLL_dodulieuNV.dodulieuNV(tbl_nhanvien);
    } else {
        thongbao.thongbao("Dữ liệu không hợp lệ!", "Cảnh báo");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_luongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_luongKeyReleased
        
        String chuoi = txt_luong.getText();
        double so = BLL.ChuyenDoi.ChuyenSangSo(chuoi);
        String sotien = BLL.ChuyenDoi.DinhDangSo(so);
        txt_luong.setText(sotien);
    }//GEN-LAST:event_txt_luongKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int nutbam = JOptionPane.showConfirmDialog(new JFrame(), "bạn chắc chắn xóa?", "xóA", JOptionPane.YES_NO_OPTION);
        if (nutbam == JOptionPane.YES_OPTION) {
            int cacdong[] = tbl_nhanvien.getSelectedRows();
            for (int i = 0; i < cacdong.length; i++) {
                int maNV = Integer.parseInt(tbl_nhanvien.getValueAt(cacdong[i], 1).toString());
                DAO.DAO_nhanvien.xoaNV(maNV);
            }
            BLL.BLL_dodulieuNV.dodulieuNV(tbl_nhanvien);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public String maNV;
    private void tbl_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_nhanvienMouseClicked
        if (tbl_nhanvien.getSelectedRowCount() == 1) {
    btn_sua.setEnabled(true);
    int vitri = tbl_nhanvien.getSelectedRow();
    txt_ten.setText(tbl_nhanvien.getValueAt(vitri, 2).toString());
    cbb_gioitinh.setSelectedItem(tbl_nhanvien.getValueAt(vitri, 3));

    // ✅ Parse ngày sinh từ String sang Date
    try {
        String ns = tbl_nhanvien.getValueAt(vitri, 4).toString();
        Date ngaysinh = new SimpleDateFormat("yyyy-MM-dd").parse(ns);
        txt_ngaysinh.setDate(ngaysinh);
    } catch (Exception e) {
        txt_ngaysinh.setDate(null);
    }

    txt_sdt.setText(tbl_nhanvien.getValueAt(vitri, 5).toString());

    // ✅ Parse ngày làm
    try {
        String nl = tbl_nhanvien.getValueAt(vitri, 6).toString();
        Date ngaylam = new SimpleDateFormat("yyyy-MM-dd").parse(nl);
        txt_ngaylam.setDate(ngaylam);
    } catch (Exception e) {
        txt_ngaylam.setDate(null);
    }

    txt_luong.setText(tbl_nhanvien.getValueAt(vitri, 7).toString());
    txt_diachi.setText(tbl_nhanvien.getValueAt(vitri, 8).toString());
    txt_ghichu.setText(tbl_nhanvien.getValueAt(vitri, 9).toString());
    txt_bangcap.setSelectedItem(tbl_nhanvien.getValueAt(vitri, 10));
    maNV = tbl_nhanvien.getValueAt(vitri, 1).toString();
} else {
    btn_sua.setEnabled(false);
}
    }//GEN-LAST:event_tbl_nhanvienMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        if (tbl_nhanvien.getSelectedRowCount() != 1) {
    thongbao.thongbao("Chỉ chọn 1 dòng để sửa", "Thông báo");
} else {
    DTO.DTO_NV nv_sua = new DTO_NV();
    nv_sua.setTen(txt_ten.getText());
    nv_sua.setGioitinh(cbb_gioitinh.getSelectedItem().toString());

    // ✅ Lấy ngày sinh từ JDateChooser
    Date ngaysinhDate = txt_ngaysinh.getDate();
    if (ngaysinhDate != null) {
        nv_sua.setNgaysinh(new SimpleDateFormat("yyyy-MM-dd").format(ngaysinhDate));
    } else {
        nv_sua.setNgaysinh(null); // hoặc giá trị mặc định
    }

    nv_sua.setSdt(txt_sdt.getText());

    // ✅ Lấy ngày làm từ JDateChooser
    Date ngaylamDate = txt_ngaylam.getDate();
    if (ngaylamDate != null) {
        nv_sua.setNgaylam(new SimpleDateFormat("yyyy-MM-dd").format(ngaylamDate));
    } else {
        nv_sua.setNgaylam(null);
    }

    nv_sua.setLuong(ChuyenDoi.ChuyenSangSo(txt_luong.getText()));
    nv_sua.setDiachi(txt_diachi.getText());
    nv_sua.setGhichu(txt_ghichu.getText());
    nv_sua.setBangCap(txt_bangcap.getSelectedItem().toString());

    boolean kt = BLL.BLL_NV.ktNV_sua(nv_sua);
    if (kt) {
        DAO.DAO_nhanvien.suaNV(nv_sua, maNV);
        BLL.BLL_dodulieuNV.dodulieuNV(tbl_nhanvien);
        lammoi();
    }
}
    }//GEN-LAST:event_btn_suaActionPerformed

    private void txt_timkiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timkiemKeyReleased
      lammoi();
      String tuKhoa=txt_timkiem.getText();
      BLL.BLL_dodulieuNV.dodulieuNV_Timkiem(tbl_nhanvien, tuKhoa);
    }//GEN-LAST:event_txt_timkiemKeyReleased
    private void lammoi() {
        txt_ten.setText("");
    cbb_gioitinh.setSelectedIndex(0);
    txt_ngaysinh.setDate(null);
    txt_sdt.setText("");
    txt_ngaylam.setDate(null);
    txt_luong.setText("");
    txt_diachi.setText("");
    txt_ghichu.setText("");
    btn_sua.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_nhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_nhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JComboBox<String> cbb_gioitinh;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_nhanvien;
    private javax.swing.JComboBox<String> txt_bangcap;
    private javax.swing.JTextField txt_diachi;
    private javax.swing.JTextField txt_ghichu;
    private javax.swing.JTextField txt_luong;
    private com.toedter.calendar.JDateChooser txt_ngaylam;
    private com.toedter.calendar.JDateChooser txt_ngaysinh;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_ten;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
