/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DAO.DAO_phieuthue;
import DTO.DTO_phieuthue;
import DTO.DTO_phong;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ADMIN
 */
public class GUI_phieuThue extends javax.swing.JFrame {

    /**
     * Creates new form GUI_phieuThue
     */
    DAO_phieuthue daoPhieuThue;
    String tenPhong;
    public GUI_phieuThue(String tenPhong){
        initComponents();
        this.tenPhong = tenPhong;
        daoPhieuThue = new DAO_phieuthue();
    }
    public GUI_phieuThue() {
        initComponents();
        daoPhieuThue = new DAO_phieuthue();
    }
    public static LocalDate date = java.time.LocalDate.now();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_hoanthanh = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lbl_maphong = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_tenphong = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_giaphong = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_tenKH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        spn_tuoi = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_sdt = new javax.swing.JTextField();
        txt_CMND = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        spn_songay = new javax.swing.JSpinner();
        lbl_maNV = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_hoanthanh1 = new javax.swing.JButton();
        btn_thue = new javax.swing.JButton();
        lbl_ngaythue = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        manhanvien = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        maKHComboBox = new javax.swing.JComboBox<>();
        lbl_tennhanvien = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PHiếu thuê");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("Phiếu thuê");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_hoanthanh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_hoanthanh.setText("In Phiếu");
        btn_hoanthanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoanthanhActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hoanthanh, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, -1, 44));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Mã phòng:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        lbl_maphong.setText("0");
        lbl_maphong.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_maphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 110, 26));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Tên phòng:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        lbl_tenphong.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_tenphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 135, 30));

        jLabel4.setText("Tên Nhân Viên");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel5.setText("Giá phòng:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        lbl_giaphong.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(lbl_giaphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 220, 30));

        jLabel6.setText("Tên khách thuê:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        txt_tenKH.setEnabled(false);
        jPanel1.add(txt_tenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 218, -1));

        jLabel7.setText("Tuổi:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        spn_tuoi.setEnabled(false);
        jPanel1.add(spn_tuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 71, -1));

        jLabel8.setText("Số điện thoại:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel9.setText("Số CMND:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        txt_sdt.setEnabled(false);
        jPanel1.add(txt_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 218, -1));

        txt_CMND.setEnabled(false);
        jPanel1.add(txt_CMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 218, -1));

        jLabel10.setText("Số ngày thuê:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));
        jPanel1.add(spn_songay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 69, -1));
        jPanel1.add(lbl_maNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 120, 85, 20));

        jLabel11.setText("Ngày thuê:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        btn_hoanthanh1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_hoanthanh1.setText("Hoàn thành");
        btn_hoanthanh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoanthanh1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hoanthanh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, -1, 44));

        btn_thue.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_thue.setText("Thuê");
        btn_thue.setEnabled(false);
        btn_thue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thueActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thue, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 82, 44));
        jPanel1.add(lbl_ngaythue, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 230, -1));

        jLabel12.setText("Mã NV");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        manhanvien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        manhanvien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                manhanvienItemStateChanged(evt);
            }
        });
        manhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manhanvienActionPerformed(evt);
            }
        });
        jPanel1.add(manhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 100, -1));

        jLabel13.setText("Mã KH");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        maKHComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        maKHComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maKHComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(maKHComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, -1));
        jPanel1.add(lbl_tennhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        daoPhieuThue.getAllIdOfNhanVien(manhanvien);
        daoPhieuThue.getAllOfMaKHID(maKHComboBox);
        if (GUI.GUI_phong.trangthai.equals("dangthue")) {
            spn_songay.setEnabled(true);
            btn_hoanthanh.setEnabled(true);
        } else {
            txt_tenKH.setEnabled(true);
            txt_sdt.setEnabled(true);
            txt_CMND.setEnabled(true);
            spn_tuoi.setEnabled(true);
            btn_thue.setEnabled(true);
        }
        
        if (!tenPhong.isEmpty()){
            lbl_tenphong.setText(tenPhong);
            daoPhieuThue.getInfoPhongByTenPhong(tenPhong, lbl_maphong, lbl_giaphong);
        }

        ResultSet rs = DAO.DAO_phong.laydulieu_Theoten(GUI.GUI_phong.tenPhong);
        DTO.DTO_phong phong=new DTO_phong();
        try {
            if (rs.next()) {
                phong.setMaphong(rs.getInt("maphong"));
                phong.setTenPhong(rs.getString("tenphong"));
                phong.setDientich(rs.getInt("dientich"));
                phong.setGia(rs.getInt("gia"));
            }
        } catch (SQLException ex) {
           thongbao.thongbao("", "");
        }
        try {
            if (rs.next()) {
                lbl_maphong.setText(rs.getString("maphong"));
                lbl_tenphong.setText(rs.getString("tenphong"));
                lbl_giaphong.setText(rs.getString("gia"));
            }
        } catch (SQLException ex) {
            thongbao.thongbao("lỗi đổ dữ liệu", "thông báo");
        }
        lbl_tennhanvien.setText(BLL.BLL_dangnhap.hovaten);
        lbl_ngaythue.setDate(new Date());
        
        

    }//GEN-LAST:event_formWindowOpened

    private void btn_thueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thueActionPerformed
        DTO.DTO_phieuthue pt = new DTO_phieuthue();
        
        if (Integer.parseInt(spn_tuoi.getValue().toString()) >= 20){
            pt.setMaphong(Integer.parseInt(lbl_maphong.getText()));
        pt.setTenphong(lbl_tenphong.getText());
        pt.setTenuser(lbl_tennhanvien.getText());
        pt.setGiaphong(Double.parseDouble(lbl_giaphong.getText()));
        pt.setTenKH(txt_tenKH.getText());
            pt.setTuoi(Integer.parseInt(spn_tuoi.getValue().toString()));
            pt.setSdt(txt_sdt.getText());
        pt.setCMND(txt_CMND.getText());
        pt.setNgaythue(lbl_ngaythue.getDate());
        pt.setSongaythue(Integer.parseInt(spn_songay.getValue().toString()));
        DAO.DAO_phieuthue.them(pt);
        }
        else{
            JOptionPane.showMessageDialog(this, "Đủ 20 tuổi mới được thuê phòng");
        }
        
        if(Integer.parseInt(spn_songay.getValue().toString())<=0){
            JOptionPane.showMessageDialog(this, "Số ngày thuê không được dưới hoặc bằng 0");
        }
        
        

    }//GEN-LAST:event_btn_thueActionPerformed

    private void btn_hoanthanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoanthanhActionPerformed
        JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Lưu phiếu thuê ra Excel");
    fileChooser.setSelectedFile(new File("phieu_thue.xlsx"));

    int userSelection = fileChooser.showSaveDialog(this);
    if (userSelection != JFileChooser.APPROVE_OPTION) return;

    File fileToSave = fileChooser.getSelectedFile();

    try (Workbook workbook = new XSSFWorkbook()) {
        Sheet sheet = workbook.createSheet("Phiếu Thuê");

        // Ghi dòng tiêu đề
        Row header = sheet.createRow(0);
        header.createCell(0).setCellValue("Thông tin phiếu thuê");

        // Dữ liệu: mỗi cặp label - value là 1 dòng
        int rowIndex = 2;

        rowIndex = createRow(sheet, rowIndex, "Mã phòng", lbl_maphong.getText());
        rowIndex = createRow(sheet, rowIndex, "Tên phòng", lbl_tenphong.getText());
        rowIndex = createRow(sheet, rowIndex, "Tên nhân viên", lbl_tennhanvien.getText());
        rowIndex = createRow(sheet, rowIndex, "Mã NV", lbl_maNV.getText());
        rowIndex = createRow(sheet, rowIndex, "Giá phòng", lbl_giaphong.getText());
        rowIndex = createRow(sheet, rowIndex, "Tên khách thuê", txt_tenKH.getText());
        rowIndex = createRow(sheet, rowIndex, "Tuổi", spn_tuoi.getValue().toString());
        rowIndex = createRow(sheet, rowIndex, "Số điện thoại", txt_sdt.getText());
        rowIndex = createRow(sheet, rowIndex, "Số CMND", txt_CMND.getText());
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        rowIndex = createRow(sheet, rowIndex, "Ngày thuê", sdf.format(lbl_ngaythue.getDate()));

        rowIndex = createRow(sheet, rowIndex, "Số ngày thuê", spn_songay.getValue().toString());

        // Ghi file
        FileOutputStream fileOut = new FileOutputStream(fileToSave);
        workbook.write(fileOut);
        fileOut.close();

        JOptionPane.showMessageDialog(this, "Xuất phiếu thuê thành công!");
    } catch (Exception ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Lỗi khi ghi file Excel: " + ex.getMessage());
    }
    }//GEN-LAST:event_btn_hoanthanhActionPerformed
    private int createRow(Sheet sheet, int rowIndex, String label, String value) {
        Row row = sheet.createRow(rowIndex);
        row.createCell(0).setCellValue(label);
        row.createCell(1).setCellValue(value);
        return rowIndex + 1;
}
    private void btn_hoanthanh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoanthanh1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btn_hoanthanh1ActionPerformed

    private void manhanvienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_manhanvienItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_manhanvienItemStateChanged

    private void manhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manhanvienActionPerformed
        if (manhanvien.getSelectedItem() != null) {
            try {
                int id = Integer.parseInt(manhanvien.getSelectedItem().toString());
                daoPhieuThue.getTenNhanVienByID(id, lbl_tennhanvien); // Gọi hàm đã viết
            } catch (NumberFormatException ex) {
                thongbao.thongbao("Mã nhân viên không hợp lệ", "Lỗi");
            }
        }
    }//GEN-LAST:event_manhanvienActionPerformed

    private void maKHComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maKHComboBoxActionPerformed
        if (maKHComboBox.getSelectedItem() != null) {
            try {
                int id = Integer.parseInt(maKHComboBox.getSelectedItem().toString());
                daoPhieuThue.getInfoByMaKHID(id, txt_tenKH, txt_sdt, txt_CMND); // Gọi hàm đã viết
            } catch (NumberFormatException ex) {
                thongbao.thongbao("Mã nhân viên không hợp lệ", "Lỗi");
            }
        }
    }//GEN-LAST:event_maKHComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ParseException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_phieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_phieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_phieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_phieuThue.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_phieuThue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hoanthanh;
    private javax.swing.JButton btn_hoanthanh1;
    private javax.swing.JButton btn_thue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_giaphong;
    private javax.swing.JLabel lbl_maNV;
    private javax.swing.JLabel lbl_maphong;
    private com.toedter.calendar.JDateChooser lbl_ngaythue;
    private javax.swing.JTextField lbl_tennhanvien;
    private javax.swing.JLabel lbl_tenphong;
    private javax.swing.JComboBox<String> maKHComboBox;
    private javax.swing.JComboBox<String> manhanvien;
    private javax.swing.JSpinner spn_songay;
    private javax.swing.JSpinner spn_tuoi;
    private javax.swing.JTextField txt_CMND;
    private javax.swing.JTextField txt_sdt;
    private javax.swing.JTextField txt_tenKH;
    // End of variables declaration//GEN-END:variables
}
