/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class GUI_loaiKH extends javax.swing.JFrame {

    /**
     * Creates new form GUI_loaiKH
     */
    public GUI_loaiKH() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txt_tenLoai = new javax.swing.JTextField();
        txt_mota = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_loaiKH = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Loại khách hàng");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(218, 6, -1, 41));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(txt_tenLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 82, 224, 34));
        jPanel1.add(txt_mota, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 224, 30));

        jLabel2.setText("Tên loại");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 48, -1, -1));

        jLabel3.setText("Mô tả");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 48, -1, -1));

        tbl_loaiKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã loại", "Tên loại", "Mô tả"
            }
        ));
        tbl_loaiKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_loaiKHMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_loaiKH);
        if (tbl_loaiKH.getColumnModel().getColumnCount() > 0) {
            tbl_loaiKH.getColumnModel().getColumn(0).setMinWidth(50);
            tbl_loaiKH.getColumnModel().getColumn(0).setPreferredWidth(50);
            tbl_loaiKH.getColumnModel().getColumn(0).setMaxWidth(50);
            tbl_loaiKH.getColumnModel().getColumn(1).setMinWidth(100);
            tbl_loaiKH.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbl_loaiKH.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 247, 666, 163));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 178, 80, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(299, 178, 70, 30));

        btn_sua.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_sua.setText("Sửa");
        btn_sua.setEnabled(false);
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 178, 70, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 53, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String tenloai = txt_tenLoai.getText();
        String mota = txt_mota.getText();
        boolean kt = BLL.BLL_KH.ktLoaiKH(tenloai, mota);
        if (kt) {
            DAO.DAO_khachhang.themLOaiKH(tenloai, mota);
        } else {
        }
        BLL.BLL_dodulieuLoai.dodulieuLoai(tbl_loaiKH);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        BLL.BLL_dodulieuLoai.dodulieuLoai(tbl_loaiKH);
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int nutbam = JOptionPane.showConfirmDialog(new JFrame(), "bạn chắc chắn xóa?", "xóA", JOptionPane.YES_NO_OPTION);
        if (nutbam == JOptionPane.YES_OPTION) {
            int cacdong[] = tbl_loaiKH.getSelectedRows();
            for (int i = 0; i < cacdong.length; i++) {
                int maLoaiKH = Integer.parseInt(tbl_loaiKH.getValueAt(cacdong[i], 1).toString());
                DAO.DAO_khachhang.xoaLoaiKH(maLoaiKH);
            }
            BLL.BLL_dodulieuLoai.dodulieuLoai(tbl_loaiKH);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public static int malOaiKH;
    private void tbl_loaiKHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_loaiKHMouseClicked
        if (tbl_loaiKH.getSelectedRowCount() == 1) {
            btn_sua.setEnabled(true);
            int vitri = tbl_loaiKH.getSelectedRow();
            txt_tenLoai.setText(tbl_loaiKH.getValueAt(vitri, 2).toString());
            txt_mota.setText(tbl_loaiKH.getValueAt(vitri, 3).toString());
            malOaiKH = (int) tbl_loaiKH.getValueAt(vitri, 1);
        } else {
        }
    }//GEN-LAST:event_tbl_loaiKHMouseClicked

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        if (tbl_loaiKH.getSelectedRowCount() != 1) {
            thongbao.thongbao("chỉ chọn 1 dòng để sửa", "thông báo");
        } else {
            
            String tenloai = txt_tenLoai.getText();
            String mota = txt_mota.getText();
            boolean kt = BLL.BLL_KH.ktLoaiKH(tenloai, mota);
            if (kt) {
                DAO.DAO_khachhang.updateLoai(malOaiKH, tenloai, mota);
            } else {
            }
            BLL.BLL_dodulieuLoai.dodulieuLoai(tbl_loaiKH);
            txt_mota.setText("");
            txt_tenLoai.setText("");
        }
    }//GEN-LAST:event_btn_suaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_loaiKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_loaiKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_loaiKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_loaiKH.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_loaiKH().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_loaiKH;
    private javax.swing.JTextField txt_mota;
    private javax.swing.JTextField txt_tenLoai;
    // End of variables declaration//GEN-END:variables
}
