/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package GUI;

import DAO.DAO_KhachHang_ThongKe;

/**
 *
 * @author huynh
 */
public class ThongKeKhachHang extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThongKeKhachHang
     */
    DAO_KhachHang_ThongKe dAO_KhachHang_ThongKe;
    public ThongKeKhachHang() {
        initComponents();
        dAO_KhachHang_ThongKe = new DAO_KhachHang_ThongKe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieChart = new javax.swing.JPanel();
        pieChart2 = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1090, 460));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout pieChartLayout = new javax.swing.GroupLayout(pieChart);
        pieChart.setLayout(pieChartLayout);
        pieChartLayout.setHorizontalGroup(
            pieChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        pieChartLayout.setVerticalGroup(
            pieChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(pieChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        javax.swing.GroupLayout pieChart2Layout = new javax.swing.GroupLayout(pieChart2);
        pieChart2.setLayout(pieChart2Layout);
        pieChart2Layout.setHorizontalGroup(
            pieChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        pieChart2Layout.setVerticalGroup(
            pieChart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        getContentPane().add(pieChart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 540, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        dAO_KhachHang_ThongKe.viewCustomerByType( pieChart);
        dAO_KhachHang_ThongKe.viewCustomerByGender(pieChart2);
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pieChart;
    private javax.swing.JPanel pieChart2;
    // End of variables declaration//GEN-END:variables
}
